import Frontier.CostModel

/-!
# Frontier.CHD.RawGen — literal, axiom-free twins of closed programs (owner agent-09, NON-GATE)

A program written with instance records (e.g. B-LAB's `labI`, whose field *types* use classical
decidability) is a closed computable `Stmt`, but `#print axioms` of its constant lists
`Classical.choice` through those types.  `genRaw` prints the program's normal form (`repr`) into a
Lean file as a literal definition plus an `rfl` bridge to the original constant; the literal has
no axioms at all.  Usage (in a scratch file that imports the program):

    #eval Frontier.RAM.genRaw "myProgRaw" myProg "/path/MyProgRaw.lean" "My.Module" "My.myProg"

then compile / install `/path/MyProgRaw.lean`.  Used for `BL2Inst.fpAtRaw` (2656 lines, compiles
in seconds).
-/

namespace Frontier.RAM

/-- Write `import imp; def name : Stmt := <repr prog>; theorem name_eq : orig = name := rfl`. -/
def genRaw (name : String) (prog : Stmt) (path imp orig : String) : IO Unit := do
  let body := (toString (repr prog)).splitOn "\n" |>.map (fun l => "  " ++ l)
  let txt := "import " ++ imp ++ "\n\nset_option maxRecDepth 100000\n\n" ++
    "/-- Literal twin of `" ++ orig ++ "` (generated by `Frontier.RAM.genRaw`; no axioms). -/\n" ++
    "def " ++ name ++ " : Frontier.RAM.Stmt :=\n" ++ String.intercalate "\n" body ++ "\n\n" ++
    "theorem " ++ name ++ "_eq : " ++ orig ++ " = " ++ name ++ " := rfl\n"
  IO.FS.writeFile path txt

/-- The same for a whole `Program` (body, word exponent, procedure table):
`def name : Program := <repr prog>; theorem name_eq : orig = name := rfl`. -/
def genRawProg (name : String) (prog : Program) (path imp orig : String) : IO Unit := do
  let body := (toString (repr prog)).splitOn "\n" |>.map (fun l => "  " ++ l)
  let txt := "import " ++ imp ++ "\n\nset_option maxRecDepth 100000\n\n" ++
    "/-- Literal twin of `" ++ orig ++ "` (generated by `Frontier.RAM.genRawProg`; no axioms). -/\n" ++
    "def " ++ name ++ " : Frontier.RAM.Program :=\n" ++ String.intercalate "\n" body ++ "\n\n" ++
    "theorem " ++ name ++ "_eq : " ++ orig ++ " = " ++ name ++ " := rfl\n"
  IO.FS.writeFile path txt

end Frontier.RAM
