-- Frontier root module (owner: agent-10). Integration of lane modules that COMPILE.
-- NO gate theorem (A/B/C/E/F) is established by anything imported here yet; see FORMALIZATION_STATUS.md.
import Frontier.Spec
import Frontier.CostModel
import Frontier.Audit
import Frontier.AuditBridge
import Frontier.RAMLogic
import Frontier.RAMWitness
import Frontier.LowerBound
import Frontier.SpecGen
import Frontier.SpecBridge
import Frontier.CHD.Basic
import Frontier.CHD.Preprocess
import Frontier.CHD.WalkOrder
import Frontier.GateCCalc
import Frontier.GateC
import Frontier.AuditGateC
import Frontier.CHD.Dispatch
import Frontier.CostSkeleton
import Frontier.CHD.BM
import Frontier.CHD.FindPivots
import Frontier.CHD.Select
import Frontier.CostCharging
import Frontier.CostAggregate
import Frontier.CostFinal
import Frontier.Density
import Frontier.RAMRep
import Frontier.Refine
import Frontier.CHD.DBlocks
import Frontier.CHD.Partition
import Frontier.RAMWP
import Frontier.CHD.BMCost
import Frontier.CHD.BMTrace
import Frontier.CHD.MLabel
import Frontier.CHD.LabTab
import Frontier.CHD.LabRAM
import Frontier.Homes
import Frontier.CHD.BMLazy
import Frontier.CHD.BSearch
import Frontier.CHD.BaseGlue
import Frontier.CHD.CostLog
import Frontier.CHD.CrBe
import Frontier.CHD.DLazy
import Frontier.CHD.FPBind
import Frontier.CHD.FPDel
import Frontier.CHD.FPForeign
import Frontier.CHD.FPIface
import Frontier.CHD.FPWQ
import Frontier.CHD.IHeap
import Frontier.CHD.LabI
import Frontier.CHD.LoopCost
import Frontier.CHD.MergeSort
import Frontier.CHD.MergeTotal
import Frontier.CHD.PartitionRAM
import Frontier.CHD.PartitionRAM2
import Frontier.CHD.PartitionRAM3
import Frontier.CHD.RamBase
import Frontier.CHD.RamBaseCase
import Frontier.CHD.RamLevel
import Frontier.CHD.RamSlot
import Frontier.CHD.RecFPLog
import Frontier.CHD.Reselect
import Frontier.CHD.SlotList
import Frontier.CHD.SpineBridge
import Frontier.CHD.BL2Extract
import Frontier.CHD.BL2HeapDel
import Frontier.CHD.BL2Loop
import Frontier.CHD.BL2Rep
import Frontier.CHD.BL2Scan
import Frontier.CHD.BL2ScanSpec
import Frontier.CHD.BL2Search
import Frontier.CHD.BL2SearchRound
import Frontier.CHD.BL2SearchSpec
import Frontier.CHD.BL2SearchStep
import Frontier.CHD.BL2StepA
import Frontier.CHD.BL2StepB
import Frontier.CHD.BL2StepC
import Frontier.CHD.BL2StepD
import Frontier.CHD.BL2StepE
import Frontier.CHD.BL2StepF
import Frontier.CHD.BL2StepG
import Frontier.CHD.BL2Tree
import Frontier.CHD.BMPlace
import Frontier.CHD.BaseHeap
import Frontier.CHD.CostLe
import Frontier.CHD.DInsertA
import Frontier.CHD.DInsertB
import Frontier.CHD.DInsertL
import Frontier.CHD.DLazySharp
import Frontier.CHD.DPsi
import Frontier.CHD.DRep
import Frontier.CHD.IHeapLab
import Frontier.CHD.LWalk
import Frontier.CHD.MarkLoop
import Frontier.CHD.PartitionRAM4
import Frontier.CHD.PartitionRAM5
import Frontier.CHD.QWit
import Frontier.CHD.QWitProv
import Frontier.CHD.QWitValid
import Frontier.CHD.SizeFacts
import Frontier.CHD.SizeParams
import Frontier.CHD.SpineBridgeD
import Frontier.CHD.TraceSize
import Frontier.CHD.TraceSizeD
import Frontier.CHD.L6.Prog
import Frontier.CHD.L6.Util
import Frontier.CHD.L6.CSort
import Frontier.CHD.L6.Keep
import Frontier.CHD.L6.DedupModel
import Frontier.CHD.L6.Dedup
import Frontier.CHD.L6.PassA
import Frontier.CHD.L6.PassB
import Frontier.CHD.L6.Layout
import Frontier.CHD.L6.Sort
import Frontier.CHD.L6.SortedRelKey
import Frontier.CHD.L6.Final
import Frontier.CHD.L6.Sizes
import Frontier.CHD.L6.Run
import Frontier.CHD.L6.Out
import Frontier.CHD.L6.TchdCn
import Frontier.CHD.L6.Body
import Frontier.CHD.L6.Params
import Frontier.CHD.BMTele
import Frontier.CHD.BMTeleChd
import Frontier.CHD.BMTeleLoop
import Frontier.CHD.BMTeleParams
import Frontier.CHD.BMTeleStep
import Frontier.CHD.DList
import Frontier.CHD.DRepExt
import Frontier.CHD.LabIC
import Frontier.CHD.RamMark
import Frontier.CHD.RelaxIns
import Frontier.CHD.SelectRAM
import Frontier.CHD.SpineLab
import Frontier.CHD.TraceFits
import Frontier.CHD.TreeRAM
import Frontier.CHD.TreeRAM2
import Frontier.CHD.TreeRAM3
import Frontier.CHD.TreeRAM4
import Frontier.CHD.TreeRAM5
import Frontier.CHD.L6.LevelTab
import Frontier.CHD.BL2InvCode
import Frontier.CHD.BL2InvInit
import Frontier.CHD.BL2InvClear
import Frontier.CHD.BL2InvFail
import Frontier.CHD.BL2InvFail2
import Frontier.CHD.BL2InvDefs
import Frontier.CHD.BL2InvStep
import Frontier.CHD.BL2InvRoot
import Frontier.CHD.BL2InvRoot2
import Frontier.CHD.BL2InvLoop
import Frontier.CHD.EntLess
import Frontier.CHD.FGroup
import Frontier.CHD.WFrame
import Frontier.CHD.TreeRAM6
import Frontier.CHD.WinScanA
import Frontier.CHD.L6.CoreTop
import Frontier.CHD.RamInit
import Frontier.CHD.RamFin
import Frontier.CHD.RamCopy
import Frontier.CHD.PartitionMap
import Frontier.CHD.TreeRAM7
import Frontier.CHD.TreeRAM8
import Frontier.CHD.BL2LX
import Frontier.CHD.BL2Find
import Frontier.CHD.MasterCost
import Frontier.Counterexamples
import Frontier.CHD.L6.SpineIface
import Frontier.CHD.L6.CoreSpecProof
import Frontier.CHD.L6.MasterSpecProof
import Frontier.CHD.L6.MasterGlue
import Frontier.CHD.AllocList
import Frontier.CHD.L6.SpineTop
import Frontier.CHD.L6.Route
import Frontier.CHD.L6.Tnat
import Frontier.CHD.CostLe2
import Frontier.CHD.TreeRAM9
import Frontier.CHD.TreeRAM10
import Frontier.CHD.FPTailCost
import Frontier.CHD.BL2Inst
import Frontier.CHD.BL2Comp
import Frontier.CHD.DGlobal
import Frontier.CHD.RamSpine
import Frontier.CHD.SpineLink
import Frontier.CHD.RamPiv
import Frontier.CHD.RamT6
import Frontier.CHD.WinScanB
import Frontier.CHD.BL2Export
import Frontier.CHD.FPComposite
import Frontier.CHD.FPFull
import Frontier.CHD.FPFullInst
import Frontier.CHD.RemoveU
import Frontier.CHD.DInsDL
import Frontier.CHD.WinScanC
import Frontier.CHD.SynFrame
import Frontier.CHD.SpineLoop
import Frontier.CHD.SpineIter
import Frontier.CHD.SpineA
import Frontier.CHD.AppendU
import Frontier.CHD.PtrScan
import Frontier.CHD.BMFresh
import Frontier.CHD.FPBridge
import Frontier.CHD.FPBridge2
import Frontier.CHD.BL2At
import Frontier.CHD.BL2Alloc
import Frontier.CHD.BL2Phi
import Frontier.CHD.BL2Call
import Frontier.CHD.BL2CallInst
import Frontier.CHD.HeapSlots
import Frontier.CHD.InsSeg
import Frontier.CHD.BaseConv
import Frontier.CHD.BaseConvDL
import Frontier.CHD.BaseCostDeg
import Frontier.CHD.BaseDHGlue
import Frontier.CHD.DRekey
import Frontier.CHD.RamBody
import Frontier.CHD.RamWp
import Frontier.CHD.WinScanD
import Frontier.CHD.WinScanE
import Frontier.CHD.WinScanF
import Frontier.CHD.L6.TopGlue
import Frontier.CHD.L6.Prologue
import Frontier.CHD.L6.ProBlow
import Frontier.CHD.L6.ProMain
import Frontier.CHD.ExecLen
import Frontier.CHD.PtrLoop
import Frontier.CHD.RamBodyA
import Frontier.CHD.RelW
import Frontier.CHD.CmpTTI
import Frontier.CHD.ReselectRAM
import Frontier.CHD.CSRSortedOf
import Frontier.CHD.BL2FPB
import Frontier.CHD.BL2Pro
import Frontier.CHD.L6.ProFinal
import Frontier.CHD.L6.FinalRoute
import Frontier.CHD.L6.FPHook
import Frontier.CHD.KeyLists
import Frontier.CHD.LabTests
import Frontier.CHD.LtBiTest
import Frontier.CHD.LtBiI
import Frontier.CHD.DMergeI
import Frontier.CHD.SpineRule
import Frontier.CHD.SpineLoopW
import Frontier.CHD.SpinePost
import Frontier.CHD.L6.NamedWitness
import Frontier.CHD.L6.LevelRoute
import Frontier.CHD.BaseCall0
import Frontier.CHD.RamBodyI
import Frontier.CHD.RamBodyF
import Frontier.CHD.WinScanG
import Frontier.CHD.BL2Hook
import Frontier.CHD.SpineFirst
import Frontier.CHD.SpineLevels
import Frontier.CHD.BL2AtRaw
import Frontier.CHD.L6.TauCap
import Frontier.CHD.L6.Assembly
import Frontier.CHD.RamBodyPro
import Frontier.CHD.RawGen
import Frontier.CHD.SpineLoopA
import Frontier.CHD.SpinePostA
import Frontier.CHD.BL2Side
import Frontier.CHD.BaseUtil
import Frontier.CHD.DLayerInst
import Frontier.CHD.DLazyFacts
import Frontier.CHD.DPro
import Frontier.CHD.DProInst
import Frontier.CHD.DPull
import Frontier.CHD.L6.DCap
import Frontier.CHD.L6.SbA
import Frontier.CHD.L6.StepInst
import Frontier.CHD.RamBodyFinDefs
import Frontier.CHD.RamBodyL
import Frontier.CHD.RamBodySpec
import Frontier.CHD.SpineLoopB
import Frontier.CHD.SpinePostB
import Frontier.CHD.SpinePostInst
import Frontier.CHD.SpinePostProof
import Frontier.CHD.SpineRegFrame
import Frontier.CHD.BL2HFP
import Frontier.CHD.BL2Step
import Frontier.CHD.DDelW
import Frontier.CHD.DLayerF
import Frontier.CHD.Final
import Frontier.CHD.L6.FinInst
import Frontier.CHD.L6.FinalGen
import Frontier.CHD.L6.SlackF
import Frontier.CHD.PullWrap
import Frontier.CHD.RamBodyFin
import Frontier.CHD.RamBodyFinB
import Frontier.CHD.SpineLoopInst

namespace Frontier
-- Agent-10 integrates the substantive theorem here only after its dependencies are proved and reviewed.
end Frontier
